# Generated by Django 2.1.7 on 2019-09-12 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_usermodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('player1', models.CharField(max_length=30)),
                ('player2', models.CharField(max_length=30)),
                ('player3', models.CharField(max_length=30)),
                ('player4', models.CharField(max_length=30)),
                ('player5', models.CharField(max_length=30)),
                ('player6', models.CharField(max_length=30)),
                ('player7', models.CharField(max_length=30)),
                ('player8', models.CharField(max_length=30)),
                ('stared_at', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TournamentModel',
            },
        ),
    ]
