# Generated by Django 2.1.7 on 2019-09-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tournamentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=30)),
                ('player2', models.CharField(max_length=30)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('round_ch', models.SmallIntegerField(choices=[(1, 'quarter'), (2, 'semifinal'), (3, 'final')], default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TournamentModel')),
            ],
        ),
    ]
