# Generated by Django 2.1.7 on 2019-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_choicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicemodel',
            name='round_ch',
            field=models.PositiveSmallIntegerField(choices=[(1, 'quarter'), (2, 'semifinal'), (3, 'final')], default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
