# Generated by Django 2.1.7 on 2019-09-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190914_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceModel',
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
