# Generated by Django 2.2.6 on 2019-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190914_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceModel',
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, ''), (8, '')], default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.PositiveSmallIntegerField(choices=[(1, ''), (2, ''), (3, ''), (4, ''), (5, ''), (6, ''), (7, ''), (8, '')], default=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
