# Generated by Django 2.1.7 on 2019-09-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190917_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
